import os
DATA_PATH="hf://datasets/VashuTheGreat2/E-Commerce-Product-Recommendation/data.csv"
ARTIFACT_FOLDER="artifacts"
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
DATA_ARTIFACT_FOLDER_NAME = "data_ingestion"
DATA_ARTIFACT_FILE_NAME = "data.csv"
VECTOR_STORE_SAVING_DIR_PATH = os.path.join(ARTIFACT_FOLDER, "transformation", "vector_db")
VECTOR_DB_PATH=os.path.join(VECTOR_STORE_SAVING_DIR_PATH, "fiase")
LOGS_DIR = "logs"
BATCH_SIZE = 500
SCHEMA_FILE_PATH = os.path.join("src", "config", "data_validation.yml")
DATA_VALIDATION_ARTIFACT_DIR_NAME = "validation"
DATA_VALIDATION_ARTIFACT_FILE_NAME = "output.yaml"
IMAGE_DOWNLOAD_DIR = os.path.join(ARTIFACT_FOLDER, "data_transformation", "images")
RANDOM_STATE = 142
TRANSFORMED_ARTIFACT_DIR = os.path.join(ARTIFACT_FOLDER, "data_transformation")
TEST_AND_VAL_SPLIT = 0.3
TRAIN_FILE_NAME = "train.csv"
TEST_FILE_NAME = "test.csv"
VAL_FILE_NAME = "val.csv"
